import React from "react";
import Page from "../components/Page";
import Head from "next/head";



export default function Home() {
  return (
    <div className="page">
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Page />
     
   </div>
  );
}
